DROP TABLE IF EXISTS TBL_MOVIE;
 
CREATE TABLE TBL_MOVIE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  NAME_OF_MOVIE VARCHAR(250) NOT NULL,
  NAME_OF_DIRECTOR VARCHAR(250) NOT NULL,
  TYPE_OF_MOVIE VARCHAR(250) DEFAULT NULL
);